language: node_js
node_js:
- 10
script:
- yarn build
- yarn test
deploy:
  provider: npm
  email: torsten.schlieder@gmx.net
  api_key:
    secure: "UjIYQ0LVSRAhXKMDsfeYRQ1MftYvBIt0b6ysity+E3B23qCarIs5TS4seKAt+5AJ3pGp6IULWX7UMQUXzeBjPPS18ZZGy77RqTYDEXBn596NlneIKEGJA/Dx0VFUkuatSGUYYbzR1rqlUdkA+XJBTNFF0oDsfcMc/CAHb/ZqbS9Y7NFHynIgIe9F3GUwUvutS+/b+wXKWKHChcXDmO/D49WQDw2ZJzSNA2w4xpJ+soA/lc4AImosyR7bYE4sJqF5QTmzIPQh0RnQtohqKQOcZ7bXUPokbVrYHzGjbBdzKAVFuflMS5HmulwHRH0QyNwVM++lYXxao48b8jSJhrHRLUk+E5R3xLSsf0ER94xE1624Eah/GgJHdyPN9MELQjIFUhYebWVxDVZ4C0h2Cj0fg9t3myavDYDzDFdrHeInr5BBNqamQkpvzD3NSt4NhxRxxidtZqj3LirP7QYcNpT67oEcFHHvu/Skjoiq16ouYAd0zsTJuvqS9ufN9IXeVWXTPfgb8R20yM1GJvKdEihTsMnZmHAJHB7tqVKOe73ywjC6Iw+/xoSWypG6rMMl1Iz9qtBLZ/FpDkHyMIqvQsgz1cWl31PL4Tq+bT5N13igXwvq3DrR6dr8zOjghe4PM/Oedde0q7l0Z39FQOcnj4iVbpKnnvvBfVx0R7LFm1IVnYs="
  on:
    tags: true
