language: node_js
node_js:
- 10
script:
- yarn build
- yarn test
deploy:
  provider: npm
  email: "torsten.schlieder@gmx.net"
  api_key: "dSdZIy61uZZG11ld5K2Fy0AYFnGRqlD9OB76rws0X2tW56J7LSpoXsUG0gJdU3+oXKyxWPRWkXJ/YaAmVL8K9HFVabmNvToxweRaPLncLcDmM3+X+z2/mgQhM0IOk4Fm+UHEEk8DymlYGGmFJ6UbeWRtQsV6AkMP1rk3UXas1iXpNqHb5nxr0xDXeacSSsdWPinLyvS9istuJL7VsQOXNrrk1S4UXo60iT9RtCNAGkXEWs5R48XdetLvnhLwbcdeHNTJjDwOIEOX5Ij3v9bKucnnMrKGpJrig9/LR/GkjD3a71Iiv2OUigkh3fDnBG5rQdosc+kJz7dQDoPW6CgkDhwnwQZYL8ljK9G1V7U+r865CPstA3SUSQIECJVQJuzKdALRi+8EnC1qkXLuFQaVANrPAkh4EprM/xt1q8RWte5gVv/w/clUfZ5/WdpuYMTWOkhRCp+aVHMy+dcnHLK9l6e7mwh2fuGpKcybHvugeJ4uguLqKhQ9JYeNiw9c/bPz5vGlXIs1u4iFbKgBP5oisZ2Y8bIVTqV4zdq5MFoYraoV8sOFrorZRDZ5gb2C4/sMHeVepyg0zTV1yct/aHlh+RE0kkf47YAV1Oxu/utZ8hi1mq2iNqGPI9QchLNgmGLWn+m0S3H88nL56CdSb3MZKdC9rDsdVTa7QY0J6plcfTM="
  on:
    tags: true
