language: node_js
node_js:
- 10
script:
- yarn build
- yarn test
deploy:
  provider: npm
  skip_cleanup: true
  email: torsten.schlieder@gmx.net
  api_key:
    secure: NMjtcip1WHY0f1Z8GpZmSGlHs5PZw5J6PDJGTQvj6aRexQGib87Icp6YIDs1ABoi7Ms+EO/9Uy2kKNWxNe2vI3ngbxT2d1HkXj0KrP8ClDcfRF3PUlbOHZky/N4YqT6CQkSsG+rnOO7F9V6XyViDAKrCf/lPi/V5Me/BddRu2rZgoVkTtEVjqQiWtXe7jPKeJO8CU76Vm+MnjLMMEqKRjyP59ZPseyw+U7uj0rfnUHedOAh0yQgg5L4GpNQCcUw+rzalcEsOBX0rMfeQKwcNyUCQDDvSleVVhU/ht3BdoeeYcRJde1Vl6kWHmjSy5kJyoC2Hfje3YQsgHSNrmY0LFxViwgaGfSG9kD+Cth3/xY1vth7FiAsQE7vrh4d9hkIOO3E+G3VTP82mcb/QkVZTbSzLJoDmNjlhyi5SZAhVviHeoMCGODhHJ2IMrDPCCXgh7KNGzxl8/6056ME3EIi0nBjvmBkdjmYxg+GfX2vvxGJmmvhqQF2PQ1OvRS6bVhjAnuPvUE5oR6Iniara2lpcMdLOvSSQYbM3k3pLzaqZnDenHFn3k1agE2eZPgFycjAmZ92Gq8g5XCt2are/j1AovjqDf+E6fIIa81/nrL/PEhWAJzGMOmaRBd5NHbbEoJn4U3MEDHqxT5/plg9zeio9+TG0qjPnewyYTE0mbE8koVU=
  on:
    tags: true
